### ISSUE TITLE
Images are not properly seen from "outside"?

### ISSUE THREAD

**Issue by luuuciano** [Spuds/SMF-ILA#3]
Hi!
In the past I made a few topics using only ILA as a way to add images to it...
And the problem was that from other places (social networks that fetch content from smf RSS maybe?) images were no showed att all, instead it showed the code used internally to show it...
Is that right? there will be a way to fix it?

Best regards!

**Comment by Spuds** [comment]
I'd assume those other sites are coming in as guests ... do you have allow guest to view attachments set in permissions?  Not sure that is or is not the issue, but ILA should be following attachment permissions.

**Comment by luuuciano** [comment]
Amazing Spuds!
It was soo easy to solve...
btw, thanks a lot for ILA, it is really helpful!
